Feature/auth
nein-tanuki/rails-base-project pull request #1
Opened 2022-02-27 06:39 UTC by nein-tanuki

## Changelog

### Models

- Added Admin
    - email: string
    - password : string (encrypted)

- Added User
    - email: string
    - password : string (encrypted)

- Added JwtDenyList
    Stores revoked jwt tokens
     - jti: string
     - exp: datetime

- Enabled uuid generation on primary keys of models Admin and User

### Controllers

- Added `registrations` and `sessions` controller for both user and admin
- Added `members` controller

#### Notes:
 - The members controller is generated to test protected endpoints. It will be removed later
 - [IMPORTANT] In registrations and sessions controller (both user and admin), you can find in **line 3** the code `skip_before_action :verify_authenticity_token`. This is used to prevent rails from verifying csrf tokens that's served on the front-end of our application. Since, the application has no front-end yet, it is advisable to disable this feature. It will be enabled once the front-end is done.

### Routes

- Added the following routes:

    `users` - registers user
    `users/sign_in` - signs in user
    `users/sign_out` - signs out user
    `admin` - registers admin
    `admin/sign_in` - signs in admin
    `admin/sign_out` - signs out admin
    `members-data` - get members endpoint

### Updated Gems/Packages

- Added the following gems/packages
```
gem 'devise-jwt'
gem 'dotenv-rails', groups: [:development, :test]
gem 'rack-cors'
```

### Development

- Added .env.example file

### Bugs/Issues

None

### References
[Resolving the ActionController::Invalid AuthenticityToken Error in a Rails/React App](https://dev.to/lizlaffitte/resolving-the-actioncontroller-invalidauthenticitytoken-error-in-a-rails-react-app-17m6)
[React-Rails authentication API with Devise and Devise-jwt](https://devsday.ru/blog/details/52846)

2022-03-05 02:37 UTC, analyn-cajocson requested changes

2022-03-05 02:37 UTC, analyn-cajocson commented on app/controllers/admins/registrations_controller.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/controllers/admins/sessions_controller.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/controllers/members_controller.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/controllers/users/confirmations_controller.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/controllers/users/registrations_controller.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/controllers/users/sessions_controller.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/components/AuthExtension.jsx
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/components/Login.jsx
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/components/Register.jsx
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/components/SideBar.jsx
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/config/theme.js
> +});
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/index.css
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/pages/App.js
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/pages/ConfirmRequired.js
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/pages/Dashboard.js
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/javascript/packs/pages/User.js
> +}
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on app/models/jwt_denylist.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on config/database.yml
> +  detabase: rails_project_production
you don't have to include this file on your PR. we already have the `database.yml.sample`

2022-03-05 02:37 UTC, analyn-cajocson commented on db/migrate/20220225034320_create_jwt_denylist.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on spec/requests/admin_spec.rb
> +end
add new line at the end of file

2022-03-05 02:37 UTC, analyn-cajocson commented on spec/requests/user_spec.rb
> +end
add new line at the end of file

2022-03-06 11:08 UTC, nein-tanuki commented on app/controllers/admins/registrations_controller.rb
> +end
Adds new line at the end of the file

2022-03-06 13:26 UTC, nein-tanuki commented on app/controllers/admins/sessions_controller.rb
> +end
added new line

2022-03-06 13:26 UTC, nein-tanuki commented on app/controllers/members_controller.rb
> +end
added new line

2022-03-06 13:26 UTC, nein-tanuki commented on app/controllers/users/confirmations_controller.rb
> +end
added new line

2022-03-06 13:26 UTC, nein-tanuki commented on app/controllers/users/registrations_controller.rb
> +end
added new line

2022-03-06 13:26 UTC, nein-tanuki commented on app/models/jwt_denylist.rb
> +end
added new line

2022-03-06 13:27 UTC, nein-tanuki commented on db/migrate/20220225034320_create_jwt_denylist.rb
> +end
added new line

2022-03-06 13:27 UTC, nein-tanuki commented on spec/requests/admin_spec.rb
> +end
added new line

2022-03-06 13:27 UTC, nein-tanuki commented on spec/requests/user_spec.rb
> +end
added new line

2022-03-06 13:28 UTC, nein-tanuki commented on app/javascript/packs/components/Register.jsx
> +}
added new line

2022-03-06 13:28 UTC, nein-tanuki commented on app/javascript/packs/components/SideBar.jsx
> +}
added new line

2022-03-06 13:28 UTC, nein-tanuki commented on app/javascript/packs/config/theme.js
> +});
added new line

2022-03-06 13:28 UTC, nein-tanuki commented on app/javascript/packs/index.css
> +}
added new line

2022-03-06 13:28 UTC, nein-tanuki commented on app/javascript/packs/pages/App.js
> +}
added new line

2022-03-06 13:29 UTC, nein-tanuki commented on app/javascript/packs/pages/ConfirmRequired.js
> +}
added new line

2022-03-06 13:29 UTC, nein-tanuki commented on app/javascript/packs/pages/Dashboard.js
> +}
added new line

2022-03-06 13:29 UTC, nein-tanuki commented on app/javascript/packs/pages/User.js
> +}
added new line

2022-03-06 14:14 UTC, nein-tanuki commented on config/database.yml
> +  detabase: rails_project_production
renamed database.yml to database.yml.sample
added config/database.yml to .gitignore

2022-03-07 11:12 UTC, analyn-cajocson approved these changes

2022-03-07 11:13 UTC, analyn-cajocson requested changes
Fix error first

2022-03-08 11:03 UTC, analyn-cajocson approved these changes

2022-03-08 11:30 UTC, justinbanaga approved these changes

2022-03-08 17:13 UTC, merged